Convert www/nginx to OpenRC service file

diff --git a/www/nginx/files/nginx.in b/www/nginx/files/nginx.in
--- a/www/nginx/files/nginx.in
+++ b/www/nginx/files/nginx.in
@@ -1,136 +1,92 @@
-#!/bin/sh
-# $FreeBSD$
+#!/sbin/openrc-run
+# Copyright 1999-2012 Gentoo Foundation
+# Distributed under the terms of the GNU General Public License v2
 
-# PROVIDE: nginx
-# REQUIRE: LOGIN cleanvar
-# KEYWORD: shutdown
+extra_commands="configtest"
+extra_started_commands="upgrade reload"
 
-#
-# Add the following lines to /etc/rc.conf to enable nginx:
-# nginx_enable (bool):		Set to "NO" by default.
-#				Set it to "YES" to enable nginx
-# nginx_profiles (str):		Set to "" by default.
-#				Define your profiles here.
-# nginx_pid_prefix (str):	Set to "" by default.
-#				When using profiles manually assign value to "nginx_"
-#				for prevent collision with other PIDs names.
-# nginxlimits_enable (bool):	Set to "NO" by default.
-#				Set it to yes to run `limits $limits_args`
-#				just before nginx starts.
-# nginx_flags (str):		Set to "" by default.
-#				Extra flags passed to start command.
-# nginxlimits_args (str):	Default to "-e -U %%WWWOWN%%"
-#				Arguments of pre-start limits run.
+description="Robust, small and high performance http and reverse proxy server"
+description_configtest="Run nginx' internal config check."
+description_upgrade="Upgrade the nginx binary without losing connections."
+description_reload="Reload the nginx configuration without losing connections."
 
-. /etc/rc.subr
+nginx_config=${nginx_config:-%%PREFIX%%/etc/nginx/nginx.conf}
 
-name="nginx"
-rcvar=nginx_enable
-
-start_precmd="nginx_precmd"
-restart_precmd="nginx_checkconfig"
-reload_precmd="nginx_checkconfig"
-configtest_cmd="nginx_checkconfig"
-gracefulstop_cmd="nginx_gracefulstop"
-upgrade_precmd="nginx_checkconfig"
-upgrade_cmd="nginx_upgrade"
 command="%%PREFIX%%/sbin/nginx"
-_pidprefix="%%NGINX_RUNDIR%%"
-pidfile="${_pidprefix}/${name}.pid"
-_tmpprefix="%%NGINX_TMPDIR%%"
-required_files=%%PREFIX%%/etc/nginx/nginx.conf
-extra_commands="reload configtest upgrade gracefulstop"
+command_args="-c ${nginx_config}"
+pidfile=${pidfile:-/var/run/nginx.pid}
+user=${user:-www}
+group=${group:-www}
 
-[ -z "$nginx_enable" ]		&& nginx_enable="NO"
-[ -z "$nginxlimits_enable" ]	&& nginxlimits_enable="NO"
-[ -z "$nginxlimits_args" ]	&& nginxlimits_args="-e -U %%WWWOWN%%"
+depend() {
+	need net
+	use dns logger netmount
+}
 
-load_rc_config $name
-
-if [ -n "$2" ]; then
-	profile="$2"
-	if [ "x${nginx_profiles}" != "x" ]; then
-		pidfile="${_pidprefix}/${nginx_pid_prefix}${profile}.pid"
-		eval nginx_configfile="\${nginx_${profile}_configfile:-}"
-		if [ "x${nginx_configfile}" = "x" ]; then
-			echo "You must define a configuration file (nginx_${profile}_configfile)"
-			exit 1
-		fi
-		required_files="${nginx_configfile}"
-		eval nginx_enable="\${nginx_${profile}_enable:-${nginx_enable}}"
-		eval nginx_flags="\${nginx_${profile}_flags:-${nginx_flags}}"
-		eval nginxlimits_enable="\${nginxlimits_${profile}_enable:-${nginxlimits_enable}}"
-		eval nginxlimits_args="\${nginxlimits_${profile}_args:-${nginxlimits_args}}"
-		nginx_flags="-c ${nginx_configfile} -g \"pid ${pidfile};\" ${nginx_flags}"
-	else
-		echo "$0: extra argument ignored"
-	fi
-else
-	if [ "x${nginx_profiles}" != "x" -a "x$1" != "x" ]; then
-		for profile in ${nginx_profiles}; do
-			echo "===> nginx profile: ${profile}"
-			%%PREFIX%%/etc/rc.d/nginx $1 ${profile}
-			retcode="$?"
-			if [ "0${retcode}" -ne 0 ]; then
-				failed="${profile} (${retcode}) ${failed:-}"
-			else
-				success="${profile} ${success:-}"
-			fi
-		done
-		exit 0
-	fi
-fi
-
-# tmpfs(5)
-nginx_checktmpdir()
-{
-	if [ ! -d ${_tmpprefix} ] ; then
-		install -d -o %%WWWOWN%% -g %%WWWGRP%% -m 755 ${_tmpprefix}
+start_pre() {
+	if [ "${RC_CMD}" != "restart" ]; then
+		configtest || return 1
 	fi
 }
 
-nginx_checkconfig()
-{
-	nginx_checktmpdir
-
-	echo "Performing sanity check on nginx configuration:"
-	eval ${command} ${nginx_flags} -t
-}
-
-nginx_gracefulstop()
-{
-	echo "Performing a graceful stop:"
-	sig_stop="QUIT"
-	run_rc_command ${rc_prefix}stop $rc_extra_args || return 1
-}
-
-nginx_upgrade()
-{
-	echo "Upgrading nginx binary:"
-
-	reload_precmd=""
-	sig_reload="USR2"
-	run_rc_command ${rc_prefix}reload $rc_extra_args || return 1
-
-	sleep 1
-
-	echo "Stopping old binary:"
-
-	sig_reload="QUIT"
-	pidfile="$pidfile.oldbin"
-	run_rc_command ${rc_prefix}reload $rc_extra_args || return 1
-}
-
-nginx_precmd() 
-{
-	nginx_checkconfig
-
-	if checkyesno nginxlimits_enable
-	then
-		eval `/usr/bin/limits ${nginxlimits_args}` 2>/dev/null
-	else
-		return 0
+stop_pre() {
+	if [ "${RC_CMD}" = "restart" ]; then
+		configtest || return 1
 	fi
 }
 
-run_rc_command "$1"
+stop_post() {
+	rm -f ${pidfile}
+}
+
+reload() {
+	configtest || return 1
+	ebegin "Refreshing nginx' configuration"
+	kill -HUP `cat ${pidfile}` &>/dev/null
+	eend $? "Failed to reload nginx"
+}
+
+upgrade() {
+	configtest || return 1
+	ebegin "Upgrading nginx"
+
+	einfo "Sending USR2 to old binary"
+	kill -USR2 `cat ${pidfile}` &>/dev/null
+
+	einfo "Sleeping 3 seconds before pid-files checking"
+	sleep 3
+
+	if [ ! -f ${pidfile}.oldbin ]; then
+		eerror "File with old pid not found"
+		return 1
+	fi
+
+	if [ ! -f ${pidfile} ]; then
+		eerror "New binary failed to start"
+		return 1
+	fi
+
+	einfo "Sleeping 3 seconds before WINCH"
+	sleep 3 ; kill -WINCH `cat ${pidfile}.oldbin`
+
+	einfo "Sending QUIT to old binary"
+	kill -QUIT `cat ${pidfile}.oldbin`
+
+	einfo "Upgrade completed"
+	eend $? "Upgrade failed"
+}
+
+configtest() {
+	checkpath -q -d -m 0755 -o root:wheel /var/log/nginx
+	checkpath -q -d -m 0755 -o ${user}:${group} /var/tmp/nginx
+	checkpath -q -d -m 0755 -o ${user}:${group} /var/tmp/nginx/{client,proxy,fastcgi,scgi,uwsgi}
+
+	ebegin "Checking nginx' configuration"
+	${command} -c ${nginx_config} -t -q
+
+	if [ $? -ne 0 ]; then
+		${command} -c ${nginx_config} -t
+	fi
+
+	eend $? "failed, please correct errors above"
+}
