Revert "Updated Enterprise repository to latest prots tree which appeared to build cleanly."
This should take up back to a time when Enterprise still builds

This reverts commit bafac166c529163500ee91840ce49d6db558f35e.

diff --git a/mail/james/files/james.in b/mail/james/files/james.in
--- a/mail/james/files/james.in
+++ b/mail/james/files/james.in
@@ -2,100 +2,95 @@
 #
 # $FreeBSD$
 #
-# PROVIDE: james
-# REQUIRE: LOGIN
-# KEYWORD: shutdown
+
 #
-# Configuration settings for james in /etc/rc.conf:
+# Configuration settings for geronimo%%GERONIMO_VERSION%% in /etc/rc.conf:
 #
-# james_enable (bool):
+# james%%JAMES_VERSION%%_enable (bool):
 #   Set to "NO" by default.
-#   Set it to "YES" to enable james
+#   Set it to "YES" to enable james%%JAMES_VERSION%%
 #
-# james_home (str)
+#
+# james%%JAMES_VERSION%%_home (str)
 #   Set to "%%JAMES_HOME%%" by default.
 #   Set the JAMES_HOME variable for the James process
 #
-# james_base (str)
+# james%%JAMES_VERSION%%_base (str)
 #   Set to "%%JAMES_HOME%%" by default.
 #   Set the JAMES_BASE variable for the James process
 #
-# james_tmpdir (str)
+# james%%JAMES_VERSION%%_tmpdir (str)
 #   Set to "/tmp" by default.
 #
-# james_stop_timeout (num)
+# geronimo%%GERONIMO_VERSION%%_stop_timeout (num)
 #   Set to "10" by default.
-#   Sets the timeout in seconds to allow james to shutdown.
-#   After the timeout has elapsed, james will be killed.
+#   Sets the timeout in seconds to allow geronimo to shutdown.
+#   After the timeout has elapsed, geronimo will be killed.
 #
-# james_java_home (str):
-# james_java_vendor (str):
-# james_java_version (str):
-# james_java_os (str):
+# james%%JAMES_VERSION%%_java_home (str):
+# james%%JAMES_VERSION%%_java_vendor (str):
+# james%%JAMES_VERSION%%_java_version (str):
+# james%%JAMES_VERSION%%_java_os (str):
 #   Specify the requirements of the Java VM to use. See javavm(1).
 #
-# james_classpath (str):
+# james%%JAMES_VERSION%%_classpath (str):
 #   Set to "" by default.
 #   Addtional classes to add to the CLASSPATH
 #
-# james_java_opts (str):
+# james%%JAMES_VERSION%%_java_opts (str):
 #   Set to "" by default.
 #   Java VM args to use.
 #
 
-james_enable="${james_enable:-"NO"}"
-james_java_version="${james_java_version:-"%%JAVA_VERSION%%"}"
-james_home="${james_home:-"%%JAMES_HOME%%"}"
-james_base="${james_base:-"%%JAMES_HOME%%"}"
-james_tmpdir="${james_tmpdir:-"/tmp"}"
-james_stop_timeout="${james_stop_timeout:-"10"}"
+james%%JAMES_VERSION%%_enable="${james%%JAMES_VERSION%%_enable:-"NO"}"
+james%%JAMES_VERSION%%_java_version="${james%%JAMES_VERSION%%_java_version:-"%%JAVA_VERSION%%"}"
+james%%JAMES_VERSION%%_home="${james%%JAMES_VERSION%%_home:-"%%JAMES_HOME%%"}"
+james%%JAMES_VERSION%%_base="${james%%JAMES_VERSION%%_base:-"%%JAMES_HOME%%"}"
+james%%JAMES_VERSION%%_tmpdir="${james%%JAMES_VERSION%%_tmpdir:-"/tmp"}"
+james%%JAMES_VERSION%%_stop_timeout="${james%%JAMES_VERSION%%_stop_timeout:-"10"}"
 
 . /etc/rc.subr
 
-name=james
-rcvar=james_enable
+name="james%%JAMES_VERSION%%"
+rcvar=james%%JAMES_VERSION%%_enable
 pidfile="%%PID_FILE%%"
+
+JAVA_HOME=%%JAVA_HOME%%
+JRE_HOME=$JAVA_HOME/jre
+
+JVM_EXT_DIRS="${james%%JAMES_VERSION%%_home}/lib:${james%%JAMES_VERSION%%_home}/tools/lib"
+JVM_OPTS="-Djava.ext.dirs=$JVM_EXT_DIRS"
 
 load_rc_config "${name}"
 
-for var in $(list_vars "james[0-9]*"); do
-        echo "WARNING: \$$var is deprecated, use \$james_${var#*_} instead."
-        eval james_${var#*_}=\"\$$var\"
-done
-
-JAVA_HOME="%%JAVA_HOME%%"
-JRE_HOME="$JAVA_HOME/jre"
-JVM_EXT_DIRS="${james_home}/lib:${james_home}/tools/lib"
-JVM_OPTS="-Djava.ext.dirs=$JVM_EXT_DIRS"
-
-if [ -n "${james_java_home}" ] ; then
-	export JAVA_HOME="${james_java_home}"
+if [ -n "${james%%JAMES_VERSION%%_java_home}" ] ; then
+	export JAVA_HOME="${james%%JAMES_VERSION%%_java_home}"
 fi
 
-if [ -n "${james_java_version}" ] ; then
-	export JAVA_VERSION="${james_java_version}"
+if [ -n "${james%%JAMES_VERSION%%_java_version}" ] ; then
+	export JAVA_VERSION="${james%%JAMES_VERSION%%_java_version}"
 fi
 
-if [ -n "${james_java_vendor}" ] ; then
-	export JAVA_VENDOR="${james_java_vendor}"
+if [ -n "${james%%JAMES_VERSION%%_java_vendor}" ] ; then
+	export JAVA_VENDOR="${james%%JAMES_VERSION%%_java_vendor}"
 fi
 
-if [ -n "${james_java_os}" ] ; then
-	export JAVA_OS="${james_java_os}"
+if [ -n "${james%%JAMES_VERSION%%_java_os}" ] ; then
+	export JAVA_OS="${james%%JAMES_VERSION%%_java_os}"
 fi
 
 if [ "$JAVA_HOME" = "" ] ; then
-	echo "ERROR: JAVA_HOME not found in your environment."
-	echo
-	echo "Please, set the JAVA_HOME variable in your environment to match the"
-	echo "location of the Java Virtual Machine you want to use."
-	return 1
+  echo "ERROR: JAVA_HOME not found in your environment."
+  echo
+  echo "Please, set the JAVA_HOME variable in your environment to match the"
+  echo "location of the Java Virtual Machine you want to use."
+  exit 1
 fi
 
-if [ -z "${james_tmpdir}" ] ; then
-	# Define the java.io.tmpdir to use for Phoenix
-	james_tmpdir="${james_home}"/temp
-	mkdir -p "${james_tmpdir}"
+if [ -z "${james%%JAMES_VERSION%%_tmpdir}" ] ; then
+  # Define the java.io.tmpdir to use for Phoenix
+  james%%JAMES_VERSION%%_tmpdir="${james%%JAMES_VERSION%%_home}"/temp
+  mkdir -p "${james%%JAMES_VERSION%%_tmpdir}"
 fi
 
 java_cmd=
@@ -107,58 +102,43 @@ fi
 
 
 java_command="$java_cmd $JVM_OPTS \
-    -Djava.security.policy=jar:file:${james_home}/bin/phoenix-loader.jar!/META-INF/java.policy \
-    -Dphoenix.home=${james_home} \
-    -Djava.io.tmpdir=${james_tmpdir} \
-    -jar ${james_home}/bin/phoenix-loader.jar >/dev/null"
+    -Djava.security.policy=jar:file:${james%%JAMES_VERSION%%_home}/bin/phoenix-loader.jar!/META-INF/java.policy \
+    -Dphoenix.home=${james%%JAMES_VERSION%%_home} \
+    -Djava.io.tmpdir=${james%%JAMES_VERSION%%_tmpdir} \
+    -jar ${james%%JAMES_VERSION%%_home}/bin/phoenix-loader.jar >/dev/null"
 
 PHOENIX_CONSOLE="$PHOENIX_TMPDIR/phoenix.console"
-if [ -z "$PHOENIX_CONSOLE" ] ; then
-	if [ -w /dev/console ]; then
-		PHOENIX_CONSOLE=/dev/console
-	else
-		PHOENIX_CONSOLE=/dev/tty
-	fi
+if [  -z "$PHOENIX_CONSOLE" ]
+then
+  if [ -w /dev/console ]
+  then
+    PHOENIX_CONSOLE=/dev/console
+  else
+    PHOENIX_CONSOLE=/dev/tty
+  fi
 fi
+
 
 # Subvert the check_pid_file procname check.
-if [ -f $pidfile ] ; then
-	read rc_pid junk < $pidfile
-	if [ ! -z "$rc_pid" ]; then
-		procname=`ps -o ucomm= $rc_pid`
-	fi
+if [ -f $pidfile ]; then
+  read rc_pid junk < $pidfile
+  if [ ! -z "$rc_pid" ]; then
+    procname=`ps -o ucomm= $rc_pid`
+  fi
 fi
 
-start_cmd=james_start
-status_cmd=james_status
-stop_cmd=james_stop
+command="/usr/sbin/daemon"
+flags="-p ${pidfile} ${java_command}"
 
-james_start() {
-	rc_pid=$(check_pidfile $pidfile *$procname*)
+start_precmd=pid_touch
+stop_cmd="james%%JAMES_VERSION%%_stop"
 
-	if [ ! -z "$rc_pid" ]; then
-		echo "Already running!"
-		return 1
-	fi
-
-	echo "Starting ${name}."
-        nohup sh -c "exec $java_command >>$PHOENIX_CONSOLE 2>&1" >/dev/null &
-        echo $! > $pidfile
+pid_touch ()
+{
+	touch $pidfile
 }
 
-james_status() {
-	rc_pid=$(check_pidfile $pidfile *$procname*)
-
-	if [ -z "$rc_pid" ]; then
-		echo "${name} not running"
-		return 1
-	else
-		echo "${name} is running as pid $rc_pid"
-		return 0
-	fi
-}
-
-james_stop() {
+james%%JAMES_VERSION%%_stop() {
 	rc_pid=$(check_pidfile $pidfile *$procname*)
 
 	if [ -z "$rc_pid" ]; then
@@ -173,7 +153,7 @@ james_stop() {
 	
 	echo "Stopping ${name}."
         kill ${rc_pid}>/dev/null
-	james_wait_max_for_pid ${james_stop_timeout} ${rc_pid}
+	james_wait_max_for_pid ${james%%JAMES_VERSION%%_stop_timeout} ${rc_pid}
 	kill -KILL ${rc_pid} 2> /dev/null && echo "Killed."
 	echo -n > ${pidfile}
 }
